all:
  hosts:
    windows:
      ansible_host: 192.168.0.242
      ansible_user: Administrator
      ansible_connection: ssh
      ansible_shell_type: powershell
      ansible_python_interpreter: C:/Users/Administrator/AppData/Local/Programs/Python/Python312/
    
linux:
  hosts:
    debian:
      ansible_host: 10.1.72.123
    fedora:
      ansible_host: 10.1.72.124
    arch:
      ansible_host: 10.1.72.157