- name: Installer msmtp
  package:
    name: msmtp
    state: present
  tags: ["msmtp", "debian", "fedora", "arch"]

- name: Configurer msmtp
  template:
    src: config.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: '0644'
  tags: ["msmtp", "debian", "fedora", "arch"]